import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import Logo from './logo.png';
import Link from 'next/link';

const nunitoSans = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <Link
          href="/"
          className="static md:absolute top-0 left-0 right-0 max-w-fit"
        >
          <Image
            src={Logo}
            alt="Logo"
            width="100"
            height="100"
            className="p-4"
          />
        </Link>
        {children}
      </body>
    </html>
  );
}
